# Simple workflow for building and deploying documentation to GitHub Pages
name: Build & deploy docs

on:
  # Runs on pushes targeting the docs folder on the main branch
  push:
    branches: ["main"]
    paths: ['docs/**', 'src/**']

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build docs and deploy them to configured server
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Build docs
        run: |
          pnpm install
          pnpm docs:build
      - name: Push Build files to prod
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete
          path: docs/public/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
          remote_key_pass: ${{ secrets.DEPLOY_SSH_PHRASE }}
