# Simple workflow for building and deploying documentation to GitHub Pages
name: Build & deploy docs to Pages

on:
  # Runs on pushes targeting the docs folder on the main branch
  push:
    branches: ["main"]
    paths: ['docs/**', 'src/**']

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build docs
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run docs:build
  # Now deploy them to configured server
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push Build files to production environment
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: docs/public/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
          remote_key_pass: ${{ secrets.DEPLOY_SSH_PHRASE }}
